Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk import pos_tag
from nltk import ne_chunk

sentences = sent_tokenize(phrase1)

for sentence in sentences:
    print("Sentence:", sentence)
    words = word_tokenize(sentence)
    pos_tags_sentence = pos_tag(words)
    ne_chunks_sentence = ne_chunk(pos_tags_sentence)
    print(ne_chunks_sentence)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mLookupError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_1736/699824466.py[0m in [0;36m<module>[0;34m[0m
[1;32m      8[0m     [0mprint[0m[0;34m([0m[0;34m"Sentence:"[0m[0;34m,[0m [0msentence[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m     [0mwords[0m [0;34m=[0m [0mword_tokenize[0m[0;34m([0m[0msentence[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 10[0;31m     [0mpos_tags_sentence[0m [0;34m=[0m [0mpos_tag[0m[0;34m([0m[0mwords[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     11[0m     [0mne_chunks_sentence[0m [0;34m=[0m [0mne_chunk[0m[0;34m([0m[0mpos_tags_sentence[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m     [0mprint[0m[0;34m([0m[0mne_chunks_sentence[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nltk/tag/__init__.py[0m in [0;36mpos_tag[0;34m(tokens, tagset, lang)[0m
[1;32m    159[0m     [0;34m:[0m[0mrtype[0m[0;34m:[0m [0mlist[0m[0;34m([0m[0mtuple[0m[0;34m([0m[0mstr[0m[0;34m,[0m [0mstr[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    160[0m     """
[0;32m--> 161[0;31m     [0mtagger[0m [0;34m=[0m [0m_get_tagger[0m[0;34m([0m[0mlang[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    162[0m     [0;32mreturn[0m [0m_pos_tag[0m[0;34m([0m[0mtokens[0m[0;34m,[0m [0mtagset[0m[0;34m,[0m [0mtagger[0m[0;34m,[0m [0mlang[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    163[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nltk/tag/__init__.py[0m in [0;36m_get_tagger[0;34m(lang)[0m
[1;32m    105[0m         [0mtagger[0m[0;34m.[0m[0mload[0m[0;34m([0m[0map_russian_model_loc[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    106[0m     [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 107[0;31m         [0mtagger[0m [0;34m=[0m [0mPerceptronTagger[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    108[0m     [0;32mreturn[0m [0mtagger[0m[0;34m[0m[0;34m[0m[0m
[1;32m    109[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nltk/tag/perceptron.py[0m in [0;36m__init__[0;34m(self, load)[0m
[1;32m    160[0m         [0;32mif[0m [0mload[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    161[0m             AP_MODEL_LOC = 'file:' + str(
[0;32m--> 162[0;31m                 [0mfind[0m[0;34m([0m[0;34m'taggers/averaged_perceptron_tagger/'[0m [0;34m+[0m [0mPICKLE[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    163[0m             )
[1;32m    164[0m             [0mself[0m[0;34m.[0m[0mload[0m[0;34m([0m[0mAP_MODEL_LOC[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nltk/data.py[0m in [0;36mfind[0;34m(resource_name, paths)[0m
[1;32m    699[0m     [0msep[0m [0;34m=[0m [0;34m'*'[0m [0;34m*[0m [0;36m70[0m[0;34m[0m[0;34m[0m[0m
[1;32m    700[0m     [0mresource_not_found[0m [0;34m=[0m [0;34m'\n%s\n%s\n%s\n'[0m [0;34m%[0m [0;34m([0m[0msep[0m[0;34m,[0m [0mmsg[0m[0;34m,[0m [0msep[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 701[0;31m     [0;32mraise[0m [0mLookupError[0m[0;34m([0m[0mresource_not_found[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    702[0m [0;34m[0m[0m
[1;32m    703[0m [0;34m[0m[0m

[0;31mLookupError[0m: 
**********************************************************************
  Resource [93maveraged_perceptron_tagger[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtaggers/averaged_perceptron_tagger/averaged_perceptron_tagger.pickle[0m

  Searched in:
    - '/home/runner/nltk_data'
    - '/opt/hostedtoolcache/Python/3.8.12/x64/nltk_data'
    - '/opt/hostedtoolcache/Python/3.8.12/x64/share/nltk_data'
    - '/opt/hostedtoolcache/Python/3.8.12/x64/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

LookupError: 
**********************************************************************
  Resource [93maveraged_perceptron_tagger[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtaggers/averaged_perceptron_tagger/averaged_perceptron_tagger.pickle[0m

  Searched in:
    - '/home/runner/nltk_data'
    - '/opt/hostedtoolcache/Python/3.8.12/x64/nltk_data'
    - '/opt/hostedtoolcache/Python/3.8.12/x64/share/nltk_data'
    - '/opt/hostedtoolcache/Python/3.8.12/x64/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


